name: Coordinator

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: xcodebuild clean test -scheme 'Coordinator' -destination "platform=iOS Simulator,name=iPhone 11,OS=latest"
